#+TITLE:Complex Variable
#+AUTHOR: Lucas Peng and Andrew Liu
#+EMAIL: lucasp0927@gmail.com andrewliu33@gmail.com
#+INCLUDE: header/header.org org
#+OPTIONS: toc:3
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}

* Complex Function
** Logrithm
\[\ln z=\log_e|z|+i(\theta+2n\pi)\]

\[\mathrm{Ln}\: z=\log_e|z|+i\mathrm{Arg}(z)\]
Undefined at $z=0$, discontinuous at $z<0$ (because of $\mathrm{Arg}(z)$)
** Sinosoid
\[\sin z=(e^{iz}-e^{-iz})/2i\]

\[\cos z=(e^{iz}+e^{-iz})/2\]

\[\sin z=\sin x\cosh y+i\cos x\sinh y\]

\[\cos z=\cos x\cosh y-i\sin x\sinh y\]

\[|\sin z|^2=\sin^2 x+\sinh^2 y\]

\[|\cos z|^2=\cos^2 x+\sinh^2 y\]

\[\sin^{-1}z=-i\ln\left[iz+\left(1-z^2\right)^{1/2}\right]\]

\[\cos^{-1}z=-i\ln\left[z+\left(1-z^2\right)^{1/2}\right]\]

\[\tan^{-1}z=\frac{i}{2}\ln\frac{i+z}{i-z}\]

** Hyperbolic Sinosoid
\[\sinh z=(e^{z}-e^{-z})/2=\sum_{n=1,\mathrm{odd}}^{\infty}\frac{z^n}{n!}\]

\[\cosh z=(e^{z}+e^{-z})/2=\sum_{n=0,\mathrm{even}}^{\infty}\frac{z^n}{n!}\]

\[\sinh z=\sinh x\cos y+i\cosh x\sin y\]

\[\cosh z=\cosh x\cos y+i\sinh x\sin y\]

\[\left| \sinh z \right|^2=\sinh^2 x+\sin^2 y\]

\[\left| \cosh z \right|^2=\cosh^2 x+\sin^2 y\]

\[\sinh^{-1}z=\ln\left[z+\left(z^2+1\right)^{1/2}\right]\]

\[\cosh^{-1}z=\ln\left[z+\left(z^2-1\right)^{1/2}\right]\]

\[\tanh^{-1}z=\frac{1}{2}\ln\frac{1+z}{1-z}\]

** Connections

\[\sinh(iz)=i\sin z\]

\[\cosh(iz)=\cos z\]

\[\sin(iz)=i \sinh z\]

\[\cos (iz) = \cosh z\]

* Cauchy-Riemann Condition
Suppose $f(z)=u(x,y)+iv(x,y)$ is differentiable at a point $z=x+iy$, then:

$\frac{\partial u}{\partial x}=\frac{\partial v}{\partial y}$ and $\frac{\partial u}{\partial y}=-\frac{\partial v}{\partial x}$
** Criterion for Analyticity
Suppose $u(x,y)$ and $v(x,y)$ are _continuous_ and have _continuous first-order partial derivatives_ in domain $D$.  If $u$ and $v$ satisfy the Cauchy-Riemann eqations at _all points_ of $D$, then the complex function $f(z)=u(x,y)+iv(x,y)$ is analytic in $D$.
** Harmonic Functions
A real-valued function $\phi(x,y)$ that has continuous second-order partial derivatives in a domain $D$ and satisfies Laplace's equation is said to be _harmonic_ in $D$.
** A Source of Harmonic Functions
Suppose $f(z)=u(x,y)+iv(x,y)$ is analytic in a domain $D$.  Then the functions $u(x,y)$ and $v(x,y)$ are harmonic functions.
* Cauchy's Integral Theorem
\[\frac{1}{2\pi i}\oint_{c}z^{n}dz=\begin{cases}
0 & \mathrm{if}\; n \neq -1 \\
1 & \mathrm{if}\; n=-1\end{cases}\]

* Cauchy Intergral Formula
Let $f$ be analytic in a simply connected domain $D$, and let $C$ be a simple closed contour lying entirely within D.  If $z_0$ is any point within $C$, then

\[f(z_0)=\frac{1}{2\pi i}\oint _{C} \frac{f(z)}{z-z_{0}}dz\]

** Derivative 
\[f^{(n)}(z_{0})=\frac{n!}{2\pi i}\oint_{C}\frac{f(z)}{(z-z_{0})^{n+1}}dz\]

** Cauchy Inequality
if $f(z)=\sum a_nz^n$ is analytic and bounded, $\left| f(z) \right|\le M$ on a circle of radius $r$ about the orogin.
, then
#+BEGIN_CENTER
\[\left| a_n \right|r^n\le M\] ,(Cauchy's inequality)
#+END_CENTER
An immediate consequence if the inequality is *Liouville's Theorem*: if $f(z)$ is analytic and bounded in the entire complex
plane it is a constant.

* Taylor and Laurent Expansion
** Taylor Expansion
Taylor expansion: about a analytic point

\[f(z)=\sum^{\infty}_{k=0}\frac{f^{(k)}(z_0)}{k!}\left(z-z_0\right)^k=\frac{1}{2\pi i}\sum_{k=0}^{\infty}\left( z-z_0 \right)^k \oint_C \frac{f(z^{\prime})\: dz^{\prime}}{\left( z^{\prime}-z_0 \right)^{k+1}}\]

** Laurent Expansion
Laurent expansion: about one singular point of $f(z)$

\[f(z)=\sum ^{\infty}_{n=-\infty}\frac{1}{2\pi i}\int \frac{f(z^{\prime})dz^{\prime}}{(z^{\prime}-z_{0})^{n+1}} \left( z-z_{0} \right)^{n}\]

** Poles 
- Simple pole: order 1
- Essential pole: order \infty
- Meroomorphic: analytic throughout the finite complex plane *except* for the isolated poles.
- Entire function: no singularities in the finite complex plane, exp: $\exp (z)$, $\sin (z)$, $\cos (z)$.
** Branch Points
$f(z)=z^a$ a is not a integer, if $a=\frac{p}{q}$, $q$ is the order of the branch point. If $a$ is irrational 
the order of the brance point is infinite. 
* Calculus of Residues
** Residue Theorem
The constant $a_{-1}$ of Laurent expansion is called /residue/ of $f(z)$ at $z=z_{0}$.
Integrate $f(z)$ by intergrate its Laurent expansion term by term. 
\begin{equation*}
\oint_C f(z) dz=\oint_C a_{n} (z-z_{0})^{n}dz=a_{-1} \oint_C (z-z_{0})^{-1}dz=2\pi i \times a_{-1}
\end{equation*}
so ,
$\frac{1}{2\pi i}\oint_C f(z) dz=a_{-1}$.

A set of isolated singularities can be handled by intergrate them clockwise, in a counterclockwise contour.

for every singular point,

$\oint f(z) dz = -2\pi i a_{-1,z_{i}}$, minus sign because of clockwise direction.

so,
\begin{equation*}
\oint f(z)dz=2\pi i\sum_{k=1}^n\textrm{Res}(f(z),z_k) 
\end{equation*}

This is called the *residue theorm*.

** Useful Trick:
\[a_{-1}=\textrm{Res}(f(z),z_0)\]

*** Simple pole
\[\textrm{Res}(f(z),z_0)=\lim_{z\to z_0}(z-z_0)f(z)\]

**** Fractial Simple Pole
\[f(z)=g(z)/h(z)\]

\[\textrm{Res}(f(z),z_0)=\frac{g(z_0)}{h^\prime(z_0)}\]

*** Pole of order n
\[\textrm{Res}(f(z).z_0)=\frac{1}{\left( m-1 \right)!} \lim_{z\to z_0}\frac{d^{m-1}}{dz^{m-1}}\left( z-z_{0} \right)^{m} f(z) \]
** Infinitesimal radius
$\int \frac{dz}{z-x_{0}}=i \int ^{2\pi}_{\pi}d\phi = i\pi$ , if counterclockwise,

$\int \frac{dz}{z-x_{0}}=i \int ^{0}_{\pi}d\phi = -i\pi$ , if clockwise.

* Pole Expantion of Meromorphic Function
Analytic function $f(z)$ that have only isolated poles as singularities are called *meromorphic*.

define: poles $z=a_{1},a_{2},a_{3},\dots$, with residues $b_{n}$

\begin{equation*}
f(z)=f(0)+\sum ^{\infty} _{n=1} b_{n} \left\{ \left( z-a_{n} \right)^{-1} +a_{n}^{-1}\right\}
\end{equation*}

- Proof:

* Product Expansion of Entire Function
- Entire Function: A function $f(z)$ that is analytic for all finite z.
if $f(z)$ has a simple zero. $f(z)=(z-a_{n})g(z)$ with $g(z)$ analytic and $g(a_{n}) \neq 0$.

\begin{equation*}
\frac{f'(z)}{f(z)}=(z-a_{n})^{-1}+\frac{g'(z)}{g(z)}
\end{equation*}

From pole expansion :
\begin{equation*}
\frac{f '(z) }{f(z)}=\frac{f' (0)}{f(0)}+\sum ^{\infty}_{n=1} \left[ \frac{1}{a_{n}}+\frac{1}{z-a_{n}} \right]
\end{equation*}

Integrate,

\begin{equation*}
\int^{z}_{0}\frac{f'(z)}{f(z)}dz=\ln f(z) -\ln f(0)=\frac{zf'(0)}{f(0)}+\sum ^{\infty}_{n=1} \left\{ \ln \left( z-a_{n} \right)-\ln \left( -a_{n} \right) +\frac{z}{a_{n}} \right\}
\end{equation*}

Exponentiating,

\begin{equation*}
f(z)=f(0) \exp \frac{z f'(0)}{f(0)}\prod^{\infty}_{n=1}\left( 1-\frac{z}{a_{n}}e^{\frac{z}{a_{n}}} \right)
\end{equation*}

** Rouche's Theorm
if $f(z)$ and $g(z)$ are analytic inside and on a closed contour C and $\left| g(z) \right| < \left| f(z) \right|$ on C then $f(z)$ and $f(z)+g(z)$ have the same number of zeros inside C.

* Evaluation of Definite Integrals
** Definite Integrals \int ^{2\pi} _{0} f(\sin \theta , cos \theta ) d \theta
\begin{eqnarray*}
I &=& \int ^{2\pi}_{0} f(\sin \theta , i\cos \theta )d \theta\\  &=& -i \int f \left( \frac{z-z^{-1}}{2i},\frac{z+z^{-1}}{2} \right)\frac{dz}{z}\\ &=& \left( -i \right)2 \pi i \times \sum (\mathrm{residues\: within\: the\: unit\: circle})
\end{eqnarray*}

Alternative,

\[\oint_C F\left(\frac{1}{2}(z+z^{-1}),\frac{1}{2i}(z,z^{-1})\right)\frac{dz}{iz}\]

** Definite Integrals \int ^{\infty}_{-\infty}f(x)dx
if 
- $f(z)$ is analytic in the upper plane and has finite number of poles.
- $f(z)$ vanishes as strong as $\frac{1}{z^{2}}$ , $0 \le arg(z) \le \pi$.

then, $I=2\pi i \times \sum \mathrm{Res}(\mathrm{upper \: plane})$

** Definite Integrals \int ^{\infty}_{-\infty} f(x)e^{iax}dx
- $f(z)$ is analytic in the upper plane and has finite number of poles.
- \[\lim_{\left|  x\right|\rightarrow \infty} f(z)=0\] , $0 \le arg(z) \le \pi$.
then, $I=2\pi i \times \sum \mathrm{residues}(\mathrm{upper \: plane})$

/Jordan's lemma/

* Other Applications of Residue
** Summation of Series by Residue Theorem
\[\sum^{\infty}_{n=-\infty}\frac{1}{P(n)}=-\pi \sum^k_{j=1}\textrm{Res}\left(\frac{\cot(\pi z)}{P(z)},z_j\right)\]

\[\sum^{\infty}_{n=-\infty}\frac{(-1)^n}{P(n)}=-\pi \sum^k_{j=1}\textrm{Res}\left(\frac{\csc(\pi z)}{P(z)},z_j\right)\]

** Inverse of Laplace Transform
\[u(t)f(t)=L^{-1}[F(z)]=\frac{1}{2\pi i}\int^{a+i\infty}_{a-i\infty}F(z)e^{zt}dz\]

\[u(t)f(t)=L^{-1}[F(z)]=\sum^{n}_{j=1}\textrm{Res}\left(e^{zt}F(z),z_j\right)\]
-----
[[file:index.org][Back to index]]
