#+TITLE: Relativity
#+AUTHOR: Lucas Peng
#+EMAIL: lucasp0927@gmail.com
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}
#+INCLUDE: header/header.org org
#+OPTIONS: toc:3

* The Geometry of Special Relativity
** Hyperbola Geometry
\[
\cosh \beta = \frac{e^\beta + e^{-\beta}}{2}
\]
\[
\sinh \beta = \frac{e^\beta - e^{-\beta}}{2}
\]
\[
\tanh \beta = \frac{\sinh\beta}{\cosh\beta}
\]
\[
\cosh^2\beta - \sinh^2\beta = 1
\]
\[
\sinh \left( \alpha + \beta \right) = \sinh \alpha \cosh \beta + \cosh \alpha \sinh \beta
\]
\[
\cosh \left( \alpha + \beta \right) = \cosh \alpha \cosh \beta + \sinh \alpha \sinh \beta
\]
\[
\tanh \left( \alpha + \beta \right) = \frac{\tanh \alpha + \tanh \beta}{1+\tanh\alpha\tanh\beta}
\]
\[
\frac{d}{d\beta} \sinh \beta = \cosh \beta
\]
\[
\frac{d}{d\beta} \cosh \beta = \sinh \beta
\]
\[
\rho^2 = x^{2 - y^2}
\]

\[
\left\{ \begin{array}{ccc}
\cosh \beta &=& \frac{x}{\rho} \\
\sinh \beta &=& \frac{y}{\rho}
 \end{array} \right.
\]
*** rotation
\[
\left( \begin{array}{c}
x\\y
\end{array} \right) = 
\left(\begin{array}{cc}
\cosh\beta & \sinh\beta\\
\sinh \beta & \cosh\beta
\end{array}\right)
\left(\begin{array}{c}
x^{\prime}\\y^{\prime}
\end{array}\right)
\]
** Lorentz Transformations
\[
v = c \tanh \beta
\]

\[
\left( \begin{array}{c}
x\\ct
\end{array} \right) = 
\left(\begin{array}{cc}
\cosh\beta & \sinh\beta\\
\sinh \beta & \cosh\beta
\end{array}\right)
\left(\begin{array}{c}
x^{\prime}\\ct^{\prime}
\end{array}\right)
\]

* Special Relativity
** Lorentz transformation
*** Four Velocity
\begin{equation*}
\mathbf{x}=X^{\mu}\left( \tau \right)= \left[ \begin{array}{c}
ct\\
x^{1}(t)\\
x^{2}(t)\\
x^{3}(t)\\
\end{array}
 \right]
\end{equation*}

**** Definition
Define $\mathbf{U}=\frac{dx}{d\tau}$, $\tau$ is proper time.

 $x^{0}=ct=c\gamma\tau$, $U^{0}=\frac{dx^{0}}{d\tau}=c\gamma$.

 $U^{i}=\frac{dx^{i}}{d\tau}=\frac{dx^{i}}{dx^{0}}\frac{dx^{0}}{d\tau}=\frac{dx^{i}}{dx^{0}}c\gamma=\frac{1}{c}\frac{dx^{i}}{d(t)}c\gamma=\gamma u^{i}$.

Where $u^{i}=\frac{dx^{i}}{dt}$.

so 
\begin{equation*}
\mathbf{U}=\gamma \left( \begin{array}{c}
 c \\
u^{1}\\
u^{2}\\
u^{3}
\end{array}
\right)
\end{equation*}

**** Interpretation
$U^{0}$ is the speed in time times c. exp: when $\gamma = 1$, $u=0$, $\mathbf{U}=\left( c,0,0,0 \right)$.

$U_{\mu}U^{\mu}=-c^{2}$

**** Note
移動物數一秒，觀察者觀察到的變化時間and位置。
*** Four Acceleration
**** Definition 
\begin{equation*}
\mathbf{A}=\frac{d\mathbf{U}}{d\tau}=\left( \gamma_{u}\dot{\gamma}_{u}c,\gamma_{u}^{2}\mathbf{a}+\gamma_{u}\dot{\gamma}_{u}\mathbf{u} \right)=\left( \gamma_{u}^{4}\frac{\mathbf{a}\cdot \mathbf{u}}{c},\gamma_{u}^{2}\mathbf{a}+\gamma_{u}^{4}\frac{\mathbf{a}\cdot \mathbf{u}}{c^{2}}u \right)
\end{equation*}
Where $\mathbf{a}=\frac{d\mathbf{u}}{dt}$ and $\dot{\gamma}_{u}=\frac{\mathbf{a}\cdot \mathbf{u}}{c^{2}}\gamma^{3}_{u}$.

Note that a dot above a variable indicates a derivative with respect to the coordinate time in a given reference frame, not the proper time \tau.
*** Four Force
**** definition
 $\mathbf{F}=\frac{d\mathbf{p}}{d \tau}$.

$\mathbf{F}=m\mathbf{A}=\left( \gamma \frac{d\gamma}{dt}mc,\gamma \frac{d}{dt}\left( \gamma m \mathbf{u} \right) \right)= \left(\gamma {d\gamma \over dt} mc,\gamma{\mathbf f}\right)$

m is the proper mass (rest mass).

** Relativistic dynamics
- tips: $\gamma \beta =  \sqrt{\gamma^{2}-1}$, 可用質量=1,c=1, Lorentz invariant 想， ($E^{2}-p^{2}m^{2}=m_{0}c^{2}$),證 $\gamma^{2}-\gamma^{2}\beta^{2}=1$.
- Relativistic momentum
\begin{equation*}
F=\frac{d}{dt}\left( mv \right)=\frac{d}{dt} \left( \frac{m_{0}v}{\sqrt{1-\frac{v^{2}}{c^{2}}}} \right)  
\end{equation*}

** Doppler effect
*** perpendicular source
 Because $k_{x}=0$, $\frac{\omega ' }{c }=\gamma \frac{\omega ' }{c}$, so $\omega ' =\omega \gamma$.
*** perpendicular observer
$k_{x}=\frac{\omega}{c}\times \beta$, $\frac{\omega ' }{c}=\gamma \left( \frac{\omega}{c}-\frac{\omega v}{c^{2}} \right)$, so $\omega ' =\sqrt{1-\beta^{2}} \omega$.

* Differential Geometry
** Vector
\[V=v^{\mu}e_{\mu}\]
set $f(x^{\mu})$ is a function that map M to $R^{1}$.  A parametrised curve $x^{\mu}\left( \lambda \right)$.

\[f \left( x^{\mu} \left( \lambda \right) \right) = g \left( \lambda \right)\]

\[\frac{d}{d\lambda}= \frac{d x^{\mu}}{d\lambda}\frac{\partial}{\partial x^{\mu}}\]

Then $\frac{dx^{\mu}}{d \lambda }$ is called component and $\frac{\partial}{\partial x^{\mu}}$ is called basis. Vectors are in tangent space.

Now, take sphere coordinate as example, $\mathbf{r} = r\sin \theta \cos \phi \: \mathbf{i} +r \sin \theta \sin \phi \:  \mathbf{j} + r cos \theta \: \mathbf{k}$

Then, we can define  $\mathbf{e}_r=\frac{\partial \mathbf{r}}{\partial r}$

*vectors and directional derivatives are one to one corresponding*

*** Lie Bracket
\[W=\left[ V,U \right]\]

\[W^n = V^i \frac{\partial U^n}{\partial x^i}-U^i\frac{\partial V^n}{\partial x^i}\]
 
A coordinate is holonomic if $\left[ e_i, e_j \right]=0$. The structure is defined as $\left[ e_i,e_j \right]=C^m_{ij}e_m$.

*** Coordinate Transform
\[V^{\prime}_{\mu} = \frac{\partial x^{\prime \mu}}{\delta x^{\lambda}}V^{\lambda}\]

\[e^{\prime}_{\mu}= \frac{\partial x^{\lambda}}{\partial x^{\prime \mu}}e^{\lambda}\]
*** Dual Vector
\omega linear map a vector to $R^1$. That is $\omega \left( \vec{a} \right)= \omega_{\alpha} a^{\alpha}$. For example \[\frac{df}{d\sigma}=\frac{dx^{\sigma}}{d\sigma}\frac{\delta f}{\partial x^{\sigma}}\].
Where $\frac{\partial f}{\partial x^{\sigma }}$ is the gradient.

\[e^{\alpha}\left( e_{\beta} \right) = \delta ^{\alpha}_{\beta}\]
** One Form
\[\nabla r=\frac{\partial r}{\partial x}\mathbf{i}+\frac{\partial r}{\partial y}\mathbf{j}+\frac{\partial r}{\partial z}\mathbf{k}=e^r\]

Dual properbility
\[e^u\cdot e_u=e^v\cdot e_v = e^w \cdot e_w =1\], \[e^u\cdot e_v=e^v\cdot e_w = e^w \cdot e_u =0\]

*One Form* \[\mathbf{\omega}=\omega_{\mu}e^{\mu}\]

\[\langle dx^{\mu}, \frac{\partial}{\partial x^{\nu}} \rangle = \delta ^{\mu} _{\nu} \]

*** Coordinate Transform
\[\theta^{\prime\mu}=\frac{\partial x^{\prime\mu}}{\partial x^{\nu}}\theta^{\nu}\]

\[\omega^{\prime}_{\nu}=\frac{\partial x^{\mu}}{x^{\prime\nu}}\omega_{\mu}\]
** Tensor
Linear map pairs of vectors to real number.
\[t \left( a,b,c \right) = t_{\alpha \beta}^{\gamma} a^{\alpha} b^{\beta} c_{\gamma}\]

*** Mertic Tensor
Product of 2 one-form. \[ds^2=g_{ik}dx^i dx^k\].
*** Absolute Differentiation
\[\frac{\partial V^{\mu}}{\partial x^{\nu}}=V^{\mu}_{,\nu}\]
\[\nabla_i V=V^m_{,i}e_m+V^me_{m,i}\], so \[\nabla V=  \left( \nabla_i V \right) \theta^i = \left( V^m_{,i}e_m+v^me_{m,i} \right) \theta^i\].
*** Connection coefficients
Define \[e_{m,i}=\Gamma^k_{mi}e_k\].

 \[\Gamma^i_{mk}=\Gamma^i_{km}\]

Define absolute differentiation \[V^{\mu}_{;\nu}=V^{\mu}_{,\nu}+\Gamma^{\mu}_{k\nu}V^k\], So that \[\nabla V=V^{\mu}_{;\nu}e_{\mu}\theta^{\nu}\]

*** Relation between \Gamma and g.

\[\Gamma^{\nu}_{\mu\kappa}= \frac{1}{2}g^{\nu\rho}\left( g_{\mu \rho ,\kappa}+g_{\kappa\rho,\mu}-g_{\mu\kappa,\rho} \right)\]

need to add 3.207.

* General Relativity
-----
[[file:index.org][Back to index]]
