#+TITLE: How To Remember Div and Curl 
#+AUTHOR: Lucas Peng
#+EMAIL: lucasp0927@gmail.com
#+INCLUDE: header/header.org org
#+OPTIONS: toc:3
#+LaTeX_HEADER: \usepackage{amssymb}
#+LaTeX_HEADER: \usepackage{amsmath}

Take spherical coordinate for example.

\[dr \Rightarrow h_1=1\]

\[d\theta \Rightarrow h_2=r\]

\[d\phi \Rightarrow h_3=r\: sin\: \theta\]

* Div
\begin{align*}
\int \nabla \cdot \mathbf{A} dV &= \int \nabla \mathbf{A} h_1 h_2 h_3 dq_1 dq_2 d q_3\\ &= \int \left\{ \frac{\partial \left( h_2h_3 dq_2 dq_3 A_1 \right)}{\partial q_1} dq_1 + \frac{\partial \left( h_1h_3 dq_1 dq_3 A_2 \right)}{\partial q_2} dq_2 + \frac{\partial \left( h_1h_2 dq_1 dq_2 A_3 \right)}{\partial q_3} dq_3  \right\}
\end{align*}

\[\nabla \cdot \mathbf{A} = \frac{1}{h_1h_2h_3}\left( \frac{\partial A_1 h_2 h_3}{ \partial q_1}+\frac{\partial A_2 h_1 h_3}{\partial q_2}+\frac{\partial A_3 h_1 h_2}{\partial q_3} \right)\]

Same as curl, devide $h_1h_2h_3$ to get the volumn. And $h_2h_3$ which is the area is what we integrate A with.

* Curl
Take 2D for example:
\begin{align*}
\int \nabla \times \mathbf{A} dA &= \int \nabla \times \mathbf{A} h_1 h_2 dq_1dq_2 \\&= \int \left\{ \frac{\partial (h_1 A_1)}{\partial q_2}dq_2 - \frac{\partial (h_2 A_2) }{\partial q_1}dq_1 \right\}
\end{align*}

\begin{equation*}
\nabla\times\mathbf{A}=
\left| 
{
\begin{array}{ccc}
\frac{\mathbf{\vec{q}_1}}{h_2 h_3} & \frac{\mathbf{\vec{q}_2}}{h_1 h_3} & \frac{\mathbf{\vec{q}_3}}{h_1 h_2}\\ 
\frac{\partial}{\partial q_1} & \frac{\partial}{\partial q_{2}} & \frac{\partial}{\partial q_{3}}\\
h_1 A_1 & h_2 A_2 & h_3 A_3\\
\end{array}
}
\right|
\end{equation*}

First row devided by  $h_2 h_3 \dots$ because while derive Curl we times $\frac{h_2h_3}{h_2h_3}$ so that we can get $h_2 h_3 dq_2 dq_3$

In third row, we time h because it is the h that times to A when doing the intergration.



------
[[file:index.org][Back to Index]]
