#+TITLE: Quantum Measurement
#+OPTIONS: toc:3
#+AUTHOR: Lucas Peng
#+EMAIL: lucasp0927@gmail.com
#+INCLUDE: header/header.org org
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}
* Spectral Theorem
Any norma, operator $\hat{N}$ has a complete set of eigenstates that are orthonormal. A normal operator is an operator such that $\left[ \hat{N},\hat{N}^{\dagger} \right] = 0$.

\[\hat{N} \left| \nu,j \right\rangle = \nu \left| \nu , j \right\rangle\]

The general diagonal form of $\hat{N}$ is $\hat{N} = \sum_{\nu}\nu \hat{\Pi}_{\nu}$. $\Pi$ is the projective operator. Hermitian operators are a special class of normal operators. It can be shown that a normal operator that is not Hermitian can be written in the form $\hat{N} = \hat{R}+ i \hat{H}$, where $\hat{R}$ and $\hat{H}$ are commuting Hermitian operators. For any two operators that commute, there is some complete basis comprising state that are eigenstates of both operators, which in this case will be a basis $\left| \nu,j \right\rangle$ diagonalizing $\hat{N}$. Operators that share eigenstates are simultaneously measurable.

Thus it is apparent that a non-Hermitian normal operator is really just a compact way to represent two simultaneously observable quantities by having eigenvalues $\nu$ in the complex plane rather than the real line. By considering vectors or other multi-component objects, any number of commuting operators can be combined to represent the corresponding simultaneously observable quantities. For projective quantum measurement theory, the important thing is not an operator representing the observables, but rather the projector $\hat{\Pi}_r$ corresponding to a result $r$.

* Projective Measurement
\[
Pr \left[ \Lambda \left( t \right) = \lambda \right] = Tr \left[ \rho \left( t \right) \hat{\Pi}_{\lambda} \right]
\]
After the measurement, the conditional (a-posteriori) state of the system is
\[
\rho \left( t+T \right) = \frac{\hat{\Pi}_{\lambda}\rho \left( t \right)\hat{\Pi}_{\lambda}}{Pr \left[  \Lambda \left( t \right) = \lambda \right]}
\]

For pure states, $\rho \left( t \right) = \left| \psi \left( t \right) \right\rangle \left\langle \psi \left( \psi \left( t \right) \right) \right|$, the above formula can be express as:

\[ 
Pr \left[ \Lambda \left( t \right) = \lambda \right] =  \left\langle \psi \left( t \right) \big| \hat{\Pi}_{\lambda} \big| \psi \left( t \right)\right\rangle
\]
 and
\[
\left| \psi_{\lambda} \left( t+T \right) \right\rangle = \hat{\Pi}_{\lambda} \left| \psi \left( t \right) \right\rangle / \sqrt{p_{\lambda}}
\]

* Systems and Meters
The projective presentation of quantum measurements is inadequate for a number of reasons.
- Very few measurement can be made in such a way that the apparatus adds no classical noise to the measurement result.
- Many measurements in which the a-posteriori conditional system is clearly not left in the eigenstate of the measured quantity corresponding to the measurement result. 

The fundamental reson why projective measurements are inadequate for describing real measurements is that experimenters never directly measure the system of interest.
- von Neumann chain
- Heisenberg's cut

Let the initial system state vector be $\left| \psi \left( t \right) \right\rangle$, it combined with second system which is called /meter/ or /apparatus/, with initial state $\left| \phi \left( t \right) \right\rangle$ thus the initial combined state is $\left| \Psi \left( t \right) \right\rangle = \left| \theta \left( t \right) \right\rangle \left| \psi \left( t \right) \right\rangle$.

\[
\left| \Psi \left( t+T_1 \right) \right\rangle = \hat{U} \left( T_1 \right) \left| \theta \left( t \right) \right\rangle \left| \psi \left( t \right) \right\rangle
\]
Meter be measured projectively over a time interval $T_2$. Let $T_1+ T_2 = T$. 

Assume evolution of the system and meter over the time $T_{2}$ is negligible.

\[
\left| \Psi_r \left( t+T \right) \right\rangle = \frac{\left| r \right\rangle \left\langle r \right| \hat{U} \left( T_1 \right) \left| \theta \left( t \right) \right\rangle \left| \psi \left( t \right) \right\rangle}{\sqrt P_{r}}
\]

See the forth equation in /projective measurement/.
------
[[file:index.org][Back to Index]]
