#+TITLE:Quantum Mechanics
#+AUTHOR: Lucas Peng
#+EMAIL: lucasp0927@gmail.com
#+INCLUDE: header/header.org org
#+OPTIONS: toc:3
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}

* Kets, Bras, and Operators
** Postulate
- first ::
$\langle\alpha\mid\beta\rangle=\langle\beta\mid\alpha\rangle^{*}$

- Second ::
$\langle\alpha\mid\alpha\rangle \ge 0$.

** Schwarz And Triangle Inequalities
\[\left| \left\langle V | W\right\rangle \right| \le \left| V \right| \left| W \right|\]

** Operators
$X\mid \alpha\rangle \Rightarrow \langle\alpha\mid X^{\dagger}$, where $X^{\dagger}$ is called *Hermitian adjoint*. A matrix is called hermitian if $X=X^{\dagger}$ .

** Multiplication
 $\left( XY \right)^{\dagger}=Y^{\dagger}X^{\dagger}$

** The Assocciative Axiom
$\left(\mid \beta\rangle\langle \alpha\mid \right)\cdot \mid \gamma\rangle = \mid \beta \rangle \cdot \left( \langle\alpha\mid\gamma\rangle \right)$.

Can prove if $X=\langle \alpha\mid\beta\rangle$, $X^{\dagger}=\langle\beta\mid \alpha\rangle$ 

\begin{equation*}
\langle \beta \mid X \mid \alpha \rangle=\langle \alpha \mid X^{\dagger} \mid \beta \rangle^{*}
\end{equation*}





* Base Kets and Matrix Representations
** Theorem 
 /The eigenvalues of a Hermitian operator A are real, the eigenket corresponding to different eigenvalue are orthogonal./
- proof ::

\begin{equation*}
A\mid a ^{\prime}   \rangle = a^{\prime}    \mid a^{\prime}    \rangle \Rightarrow \langle a^{\prime \prime} \mid A \mid a^{\prime} \rangle=a^{\prime}\langle a^{\prime \prime}\mid a^{\prime}\rangle
\end{equation*}

\begin{equation*}
\langle a^{\prime \prime}\mid A= a^{\prime \prime}\langle a^{\prime \prime}\mid \Rightarrow \langle a^{\prime \prime} \mid A \mid a^{\prime}\rangle=a^{\prime \prime}\langle a^{\prime\prime}\mid a^{\prime}\rangle
\end{equation*}

so $\left( a^{\prime\prime}-a^{\prime} \right) \langle a^{\prime \prime}\mid a^{\prime}\rangle$.

** Closure
\begin{equation*}
\Sigma_{a^{\prime}}\mid a^{\prime}\rangle \langle a^{\prime}\mid=1
\end{equation*}


* Measurements, Oberservation, and the Uncertainty Relation 
** Expectation Value
Expectation value of A taken with respect to state $\mid \alpha \rangle$.
$\langle A \rangle=\langle \alpha \mid A \mid \alpha \rangle$

Notation $\langle A \rangle_{\alpha}$ is somtimes used.

because, $\langle A \rangle = \Sigma_{a^{\prime}}\Sigma_{a^{\prime \prime}}\langle \alpha \mid a^{\prime \prime}\rangle\langle a^{\prime \prime} \mid A \mid a^{\prime} \rangle \langle a^{\prime}\mid\alpha\rangle=\Sigma_{a^{\prime}}a^{\prime}\left| \langle a^{\prime}\mid \alpha \rangle. \right|^{2}$. This is what expextation value means.

** Spin 1/2 System

* Rotation of spin one-half
** Rotate about z
\[\left( \begin{array}{cc} e^{i \phi /2}&0 \\  0 & e^{-i\phi /2}\end{array} \right)\]
** Rotate about x
\[\left( \begin{array}{cc}  \cos \phi /2  &  i \sin \phi /2 \\ i \sin \phi /2 & \cos \phi /2 \end{array} \right)\]
** Rotate about y
\[\left( \begin{array}{cc}  \cos \phi /2 & \sin \phi /2 \\ - \sin \phi /2 & \cos \phi /2 \end{array} \right)\]

* Rotational Invariance and Angular Momentum
\[
U \left[ R \left( \epsilon_z \mathbf{k} \right) \right] = \mathbf{I} - \frac{i \epsilon_z L_z}{\hbar}
\]

\[
\mathbf{L}_z = \mathbf{X}\mathbf{P}_y-\mathbf{Y}\mathbf{P}_{x}
\]

- Coordinate Basis
\[
\mathbf{L}_z = x \left( -i\hbar \frac{\partial}{\partial y} \right)-y \left( -i \hbar \frac{\partial}{\partial x} \right)
\]

- Momentum Basis
\[
\mathbf{L}_z = i\hbar \frac{\partial}{\partial p_x} p_{y}- i \hbar \frac{\partial}{\partial p_y} p_x
\]

\[
\mathbf{L}_z = -i\hbar \frac{\partial}{\partial \phi}
\]

** Eigenvalue of $L_{z}$
\[
L_z \left| l_z \right\rangle = l_z \left| l_z \right\rangle
\]
\[
l_z = m\hbar, m=0,\pm 1,\pm 2 \dots
\]

** Angular Momentum
\[
\left[ L_x,L_y \right] = i \hbar L_z
\]

This imply $\mathbf{L} \times \mathbf{L} = i\hbar \mathbf{L}$.

\[L^2 = L_x^2+L_y^2+L_z^2\]

\[
\mathbf{c}=\mathbf{a}\times \mathbf{b}
\]
\[
c_i= \epsilon_{ijk}a_j b_k
\]

** Eigenvalue Problem of $L^{2}$ and $L_{z}$
- Raising and Lower operators
\[
L_{\pm}=L_x \pm i L_y
\]

\[
\left\{
\begin{align}
\mathbf{J}^2 \left| jm \right\rangle =& j \left( j+1 \right) \hbar^2 \left| jm \right\rangle, &j=0,1/2,1\dots\\
\mathbf{J}_z \left| jm \right\rangle =& m\hbar \left| jm \right\rangle, &m=j,j-1,\dots,-j
\end{align}
\right.
\]

\[
J_{\pm} \left| jm \right\rangle = \hbar \sqrt{\left( j \mp m \right)\left( j \pm m+1 \right)} \left| j,m\pm 1 \right\rangle
\]

** Finite Rotation
\[
D^{(j)}\left[ R \left( \theta \right) \right] = \exp \left[ - \frac{i \theta \cdot \mathbf{J}^{(j)}}{\hbar} \right]
\]
* The Hydrogen Atom
** The eigenvalue problem
\[
\left\{ \frac{d^2}{dr^2}+\frac{2m}{\hbar^2}\left[ E+\frac{e^2}{r}-\frac{l \left( l+1 \right)\hbar^2}{2mr^2} \right] \right\}U_{El}=0
\]

\[
\left\{ 
\begin{align}
\Psi_{Elm}=&\frac{U_{El}}{r}Y^m_l\\
U_{El}=&e^{-\rho}v_{El}\\
v_{El}=& \rho^{l+1}\sum_{k=0}^{\infty} C_k \rho^{k}\\
\frac{C_{k+1}}{C_k}=&\frac{-e^2 \lambda + 2 \left( k+l+1 \right)}{\left( k+l+2 \right)\left( k+l+1 \right)-\left( l+1 \right)l }
\end{align}
\right.
\]

\[
\left\{
\begin{align}
\rho =& \sqrt{\frac{2mW}{\hbar^2}}r\\
\lambda =& \sqrt{\frac{2m}{\hbar^2W}}\\
\mathrm{Ry} =& \frac{me^4}{2\hbar^2}\\
a_0 =& \frac{\hbar^2}{me^2}
\end{align} 
\right.
\]

* Spin
\[
\left\{ 
\begin{align}
\mathbf{S} =& \frac{\hbar}{2}\mathbf{\sigma}\\
S_x =& \frac{\hbar}{2} \left[ \begin{array}{cc}0&1\\1&0\end{array} \right]\\
S_y =& \frac{\hbar}{2} \left[ \begin{array}{cc}0&-i\\i&0\end{array} \right]\\
S_z =& \frac{\hbar}{2} \left[ \begin{array}{cc}1&0\\0&-1\end{array} \right]
\end{align}
\right.
\]



** Properties of Pauli Matrices
- anticommute
\[
\left[ \sigma_i,\sigma_j \right]_{+}=0
\]
- $\sigma_{x}\sigma_{y}=i\sigma_{z}$
- $\mathrm{Tr} \sigma_{i}=0$
- $\left( \hat{n}\cdot\mathbf{\sigma}\right)^2=\mathbf{I}$
- Very useful identity
\[
\left( \mathbf{A}\cdot\mathbf{\sigma} \right)\left( \mathbf{B}\cdot\mathbf{\sigma} \right)=\mathbf{A}\cdot \mathbf{B} \mathbf{I}+i \left( \mathbf{A}\times \mathbf{B} \right)\cdot \mathbf{\sigma}
\]
- Commutation Relations
\[
\left[ \sigma_a,\sigma_b \right] = 2i \epsilon_{abc}\sigma_c
\]
\[
\left\{ \sigma_a.\sigma_b \right\} = 2\delta_{ab}\mathbf{I}
\]
** Explicit Forms of Rotation Operation
\[
U \left[ R \left( \theta \right) \right] = \exp \left( -i \theta\cdot S /\hbar \right)=\cos \left( \theta /2 \right)\mathbf{I}-i \sin \left( \theta /2 \right)\hat{\theta}\cdot\mathbf{\sigma}
\]
* Spin Dynamics
\[
\mathbf{T}=\mu\times \mathbf{B}
\]
- gyromagnetic ratio
\[
\mu=\gamma l, \gamma=\frac{q}{2mc}
\]
\[
H_{int}=-\mu \cdot \mathbf{B}
\]
* Addition of Angular Momenta
- Total angular momentum operator
\[
\mathbf{S}=\mathbf{S}_1+\mathbf{S}_{2}
\]

\[
\mathbf{S}^2=\left( \mathbf{S}_{1}+\mathbf{S}_{2} \right)\cdot \left( \mathbf{S}_1+\mathbf{S}_{2} \right)  =\mathbf{S}_1^2+\mathbf{S}_2^2+2\mathbf{S}_{1}\cdot \mathbf{S}_2
\]

\[
\mathbf{S}_1\cdot \mathbf{S}_2=S_{1z}S_{2z}+\frac{1}{2}\left( S_{1+}S_{2-}+S_{1-}S_{2+} \right)
\]
* The Variational and WKB Methods
** The Variationsl Method
- example consider a problem in a potential $V(x) = \lambda x^{4}$.
  trail function $\psi - e^{-\alpha x^2/2}$.
  The energy as a function of $\alpha$ is 
\[
E \left( \alpha \right) = \frac{\int e^{-\alpha x^2/2 } \left( -\frac{\hbar^2}{2m} \frac{d^2}{dx^2}+\lambda x^4 \right)e^{-\alpha x^2/2} dx}{  \int e^{-\alpha x^2} dx} = \frac{\hbar^2 \alpha}{4m}+\frac{3\lambda}{4 \alpha^{2}}
\]
- For Coulomb Potential $V=-e^{2}/r$. Trail function $\psi = \exp \left( -\alpha r^2 \right)$
\[
E \left( \alpha \right) = \frac{\int \left[ e^{-\alpha r^2} \left( -\frac{\hbar^2}{2m}\frac{1}{r^2}\frac{d}{dr}r^2 \frac{d}{dr}-\frac{e^2}{r} \right) \right]r^2 dr}{\int e^{-2\alpha r^2}r^2 dr}=\frac{3\hbar^2\alpha}{2m}-\left( \frac{2}{\pi} \right)^{1/2}2 e^2 \alpha^{1/2}
\]
- Ground state of He
\[
H= -\frac{h^2}{2m} \left( \nabla_1^2+\nabla_2^2 \right)-\frac{2e^2}{r_1}-\frac{e^2}{r_2}+\frac{e^2}{r_{12}}
\]

** WKB Method
\[
\psi \left( x \right) = \psi \left( x_0 \right) \exp \left[ \pm \left( \frac{i}{\hbar} \right)\int^x_{x_0} p \left( x^{\prime} \right)dx^{\prime} \right]
\]
\[
\psi \left( x \right) - \psi \left( x_0 \right) \left[ \frac{p \left( x_0 \right)}{p \left( x \right)} \right]^{1/2}\exp \left[ \pm \frac{i}{\hbar} \int^x_{x_0} p \left( x^{\prime} \right)dx^{\prime} \right]
\]

- Useful integration
\[
\int^b_a \sqrt{\frac{1}{x}-\frac{1}{b}}dx = \left\{ \cos^{-1} \sqrt{\frac{a}{b}} - \sqrt{\frac{a}{b} \left( 1-\frac{a}{b} \right)} \right\} \sqrt{b}
\]

\[
\int \frac{\cos^2 x}{a} dx = \frac{x+\sin x \cos x}{2a}
\]
-----
[[file:index.org][Back to Index]]

