#+TITLE:Quantum Mechanics
#+AUTHOR: Lucas Peng
#+EMAIL: lucasp0927@gmail.com
#+INCLUDE: header/header.org org
#+OPTIONS: toc:3
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}

* Kets, Bras, and Operators
** Postulate
- first ::
$\langle\alpha\mid\beta\rangle=\langle\beta\mid\alpha\rangle^{*}$

- Second ::
$\langle\alpha\mid\alpha\rangle \ge 0$.

** Schwarz And Triangle Inequalities
\[\left| \left\langle V | W\right\rangle \right| \le \left| V \right| \left| W \right|\]

** Operators
$X\mid \alpha\rangle \Rightarrow \langle\alpha\mid X^{\dagger}$, where $X^{\dagger}$ is called *Hermitian adjoint*. A matrix is called hermitian if $X=X^{\dagger}$ .

** Multiplication
 $\left( XY \right)^{\dagger}=Y^{\dagger}X^{\dagger}$

** The Assocciative Axiom
$\left(\mid \beta\rangle\langle \alpha\mid \right)\cdot \mid \gamma\rangle = \mid \beta \rangle \cdot \left( \langle\alpha\mid\gamma\rangle \right)$.

Can prove if $X=\langle \alpha\mid\beta\rangle$, $X^{\dagger}=\langle\beta\mid \alpha\rangle$ 

\begin{equation*}
\langle \beta \mid X \mid \alpha \rangle=\langle \alpha \mid X^{\dagger} \mid \beta \rangle^{*}
\end{equation*}





* Base Kets and Matrix Representations
** Theorem 
 /The eigenvalues of a Hermitian operator A are real, the eigenket corresponding to different eigenvalue are orthogonal./
- proof ::

\begin{equation*}
A\mid a ^{\prime}   \rangle = a^{\prime}    \mid a^{\prime}    \rangle \Rightarrow \langle a^{\prime \prime} \mid A \mid a^{\prime} \rangle=a^{\prime}\langle a^{\prime \prime}\mid a^{\prime}\rangle
\end{equation*}

\begin{equation*}
\langle a^{\prime \prime}\mid A= a^{\prime \prime}\langle a^{\prime \prime}\mid \Rightarrow \langle a^{\prime \prime} \mid A \mid a^{\prime}\rangle=a^{\prime \prime}\langle a^{\prime\prime}\mid a^{\prime}\rangle
\end{equation*}

so $\left( a^{\prime\prime}-a^{\prime} \right) \langle a^{\prime \prime}\mid a^{\prime}\rangle$.

** Closure
\begin{equation*}
\Sigma_{a^{\prime}}\mid a^{\prime}\rangle \langle a^{\prime}\mid=1
\end{equation*}


* Measurements, Oberservation, and the Uncertainty Relation 
** Expectation Value
Expectation value of A taken with respect to state $\mid \alpha \rangle$.
$\langle A \rangle=\langle \alpha \mid A \mid \alpha \rangle$

Notation $\langle A \rangle_{\alpha}$ is somtimes used.

because, $\langle A \rangle = \Sigma_{a^{\prime}}\Sigma_{a^{\prime \prime}}\langle \alpha \mid a^{\prime \prime}\rangle\langle a^{\prime \prime} \mid A \mid a^{\prime} \rangle \langle a^{\prime}\mid\alpha\rangle=\Sigma_{a^{\prime}}a^{\prime}\left| \langle a^{\prime}\mid \alpha \rangle. \right|^{2}$. This is what expextation value means.

** Spin 1/2 System

* Rotation of spin one-half
** Rotate about z
\[\left( \begin{array}{cc} e^{i \phi /2}&0 \\  0 & e^{-i\phi /2}\end{array} \right)\]
** Rotate about x
\[\left( \begin{array}{cc}  \cos \phi /2  &  i \sin \phi /2 \\ i \sin \phi /2 & \cos \phi /2 \end{array} \right)\]
** Rotate about y
\[\left( \begin{array}{cc}  \cos \phi /2 & \sin \phi /2 \\ - \sin \phi /2 & \cos \phi /2 \end{array} \right)\]

* Rotational Invariance and Angular Momentum
\[
U \left[ R \left( \epsilon_z \mathbf{k} \right) \right] = \mathbf{I} - \frac{i \epsilon_z L_z}{\hbar}
\]

\[
\mathbf{L}_z = \mathbf{X}\mathbf{P}_y-\mathbf{Y}\mathbf{P}_{x}
\]

- Coordinate Basis
\[
\mathbf{L}_z = x \left( -i\hbar \frac{\partial}{\partial y} \right)-y \left( -i \hbar \frac{\partial}{\partial x} \right)
\]

- Momentum Basis
\[
\mathbf{L}_z = i\hbar \frac{\partial}{\partial p_x} p_{y}- i \hbar \frac{\partial}{\partial p_y} p_x
\]

\[
\mathbf{L}_z = -i\hbar \frac{\partial}{\partial \phi}
\]

** Eigenvalue of $L_{z}$
\[
L_z \left| l_z \right\rangle = l_z \left| l_z \right\rangle
\]
\[
l_z = m\hbar, m=0,\pm 1,\pm 2 \dots
\]

** Angular Momentum
\[
\left[ L_x,L_y \right] = i \hbar L_z
\]

This imply $\mathbf{L} \times \mathbf{L} = i\hbar \mathbf{L}$.

\[L^2 = L_x^2+L_y^2+L_z^2\]

\[
\mathbf{c}=\mathbf{a}\times \mathbf{b}
\]
\[
c_i= \epsilon_{ijk}a_j b_k
\]

** Eigenvalue Problem of $L^{2}$ and $L_{z}$
- Raising and Lower operators
\[
L_{\pm}=L_x \pm i L_y
\]

\[
\left\{
\begin{array}
\mathbf{J}^2 \left| jm \right\rangle &=& j \left( j+1 \right) \hbar^2 \left| jm \right\rangle, &j=0,1/2,1\dots\\
\mathbf{J}_z \left| jm \right\rangle &=& m\hbar \left| jm \right\rangle, &m=j,j-1,\dots,-j
\end{array}
\right.
\]

\[
J_{\pm} \left| jm \right\rangle = \hbar \sqrt{\left( j \mp m \right)\left( j \pm m+1 \right)} \left| j,m\pm 1 \right\rangle
\]

** Finite Rotation
\[
D^{(j)}\left[ R \left( \theta \right) \right] = \exp \left[ - \frac{i \theta \cdot \mathbf{J}^{(j)}}{\hbar} \right]
\]

* Spin
\[
\left\{ 
\begin{array}{rl}
\mathbf{S} &=& \frac{\hbar}{2}\mathbf{\sigma}\\
S_x &=& \frac{\hbar}{2} \left[ \begin{array}{rl}&0 &1 \\ &1 &0 \end{array} \right]\\
S_y &=& \frac{\hbar}{2} \left[ \begin{array}{rl}&0 &-i \\ &i &0 \end{array} \right]\\
S_z &=& \frac{\hbar}{2} \left[ \begin{array}{rl}&1 &0 \\ &0 &-1 \end{array} \right]
\end{array}
\right.
\]



** Properties of Pauli Matrices
- anticommute
\[
\left[ \sigma_i,\sigma_j \right]_{+}=0
\]
- $\sigma_{x}\sigma_{y}=i\sigma_{z}$
- $\mathrm{Tr} \sigma_{i}=0$
- $\left( \hat{n}\cdot\mathbf{\sigma}\right)^2=\mathbf{I}$
- Very useful identity
\[
\left( \mathbf{A}\cdot\mathbf{\sigma} \right)\left( \mathbf{B}\cdot\mathbf{\sigma} \right)=\mathbf{A}\cdot \mathbf{B} \mathbf{I}+i \left( \mathbf{A}\times \mathbf{B} \right)\cdot \mathbf{\sigma}
\]
** Explicit Forms of Rotation Operation
\[
U \left[ R \left( \theta \right) \right] = \exp \left( -i \theta\cdot S /\hbar \right)=\cos \left( \theta /2 \right)\mathbf{I}-i \sin \left( \theta /2 \right)\hat{\theta}\cdot\mathbf{\sigma}
\]
* Spin Dynamics
\[
\mathbf{T}=\mu\times \mathbf{B}
\]
- gyromagnetic ratio
\[
\mu=\gamma l, \gamma=\frac{q}{2mc}
\]
\[
H_{int}=-\mu \cdot \mathbf{B}
\]
* Addition of Angular Momenta
- Total angular momentum operator
\[
\mathbf{S}=\mathbf{S}_1+\mathbf{S}_{2}
\]

\[
\mathbf{S}^2=\left( \mathbf{S}_{1}+\mathbf{S}_{2} \right)\cdot \left( \mathbf{S}_1+\mathbf{S}_{2} \right)  =\mathbf{S}_1^2+\mathbf{S}_2^2+2\mathbf{S}_{1}\cdot \mathbf{S}_2
\]

\[
\mathbf{S}_1\cdot \mathbf{S}_2=S_{1z}S_{2z}+\frac{1}{2}\left( S_{1+}S_{2-}+S_{1-}S_{2+} \right)
\]

-----
[[file:index.org][Back to Index]]

