#+TITLE: Statistical Mechanics
#+OPTIONS: toc:3
#+AUTHOR: Lucas Peng
#+EMAIL: lucasp0927@gmail.com
#+INCLUDE: header/header.org org
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{amsmath}
* Basic of Thermodynamics
** Thermal Contact
System 1 and System 2 in contact. The total multiplicity $\Omega^{(0)}=\Omega_1 \times \Omega_2$. When $\Omega^{(0)}$ max.

\[\frac{\partial \Omega_1 \left( E_1 \right)}{\delta E_1}\Omega_2+\Omega_1 \left( E_1 \right) \frac{\partial \Omega_2 \left( E_2 \right)}{\partial E_2}\cdot \frac{\partial E_2}{\partial E_1}=0 \]

where $\frac{\partial E_2}{\partial E_1}=-1$

\[
\frac{\partial \ln \left( \Omega_1 \right)}{\partial E_1} = \frac{\partial \ln \left( \Omega_2 \right)}{\partial E_2} = \beta
 \]

$S=k \ln \Omega$, $\beta = \frac{1}{kT}$. So $\left( \frac{\partial S}{\partial E} \right)_{N,V}=\frac{1}{T}$

[[file:thermodynamic_square.org][Thermodynamic Square]]

** Other contact
using $dU= TdS-PdV+\mu dN$
- $\frac{\partial \ln \Omega_1}{\partial E_1}=\frac{\partial \ln \Omega_2}{\partial E_2}=\beta=\frac{1}{kT}$
- $\frac{\partial \ln \Omega_1}{\partial V_1}=\frac{\partial \ln \Omega_2}{\partial V_2}=\eta=\frac{P}{kT}$
- $\frac{\partial \ln \Omega_1}{\partial N_1}=\frac{\partial \ln \Omega_2}{\partial N_2}=\eta=\frac{-\mu}{kT}$

** S Centric Equations
\[
\left\{
\begin{array}{rl}
  \frac{1}{T}&=&\frac{\partial S}{\delta E} \\
  \frac{P}{T}&=&\frac{\partial S}{\delta V} \\
  \frac{\mu}{T}&=&\frac{-\partial S}{\delta N}\\
\end{array} \right.
\]
** E Centric Equations
  Using $\frac{\partial x}{\partial y} \frac{\partial y}{\partial z} \frac{\partial z}{\partial x} = -1$.
\[
\left\{
\begin{array}{rl}
  T &=& \frac{\partial E}{\partial S}\\
  P &=& T \frac{\partial S}{\partial V} = \frac{\partial S}{\partial V} \times \frac{\partial E}{\partial S} = - \frac{\partial E}{\partial V}\\
  \mu &=& -T \frac{\partial S}{\partial N} = -\frac{\partial S}{\partial N} \times \frac{\partial E}{\partial S} =  \frac{\partial E}{\partial N}
\end{array}\right.
\]
** Heat capacity
\[C_v = \left( \frac{\partial E}{\partial T} \right)_{N,V} = \frac{\partial E}{\partial S} \frac{\partial S}{\partial T} = T \left( \frac{\partial S}{\partial T} \right)_{N,V}\]

\[C_P = \left( \frac{\partial H}{\partial T} \right)_{N,P} = \left( \frac{\partial E+PV}{\partial T} \right)_{N,P} = T \left( \frac{\partial S}{\partial T} \right)_{N,P}\]

** Classic Ideal Gas
\[\Omega \propto V^N \Rightarrow PV=nkT\]

\[\epsilon = \frac{h^2}{8mL^2} \left( n_x^2+n_y^2+n_z^2 \right)\]

\[n_x^2+n_y^2+n_z^2=\frac{8mV^{2/3}}{h^2}\epsilon = \epsilon^{*}\]

\[\sum_{r=1}^{3N}n_r^2= E^{*}= \frac{8, V^{2/3}E}{h^2}\]

This means that $S \left( N,V,E \right) = S \left( N,V^{2/3}E \right)$. Adiabitic process $S,N$ constant, leads to $V^{2/3}E=\mathrm{constant}$

Now compute the multiplicity of classical ideal gas.

$\Omega_N \left( E^{\star} \right)$ lattice points lying on surface of 3N-D sphere of $\sqrt{E^{\star}}$

$\Sigma_N \left( E^{\star} \right)$ lattice points lying within surface of 3N-D sphere of $\sqrt{E^{\star}}$

\[\Sigma_N \left( E^{\star} \right) = \sum_{E^{\star\prime} < E^{\star}}\Omega_N \left( E^{\star\prime} \right)\]

Volume of multidimension sphere.

\[\Sigma_N \left( E^{\star} \right) = \left( \frac{1}{2} \right)^{3N} \left\{ \frac{\pi^{3N/2}}{\left( \frac{3N}{2} \right)!}{E^{\star}}^{3N/2} \right\}\]

Using stiring approximation.

\[\ln \Sigma \left( N,V,E \right) = N \ln \left( \frac{V}{h^3}\left( \frac{4\pi m E}{3N} \right)^{3/2} \right)+\frac{3}{2}N\]

Counting points in $\Delta E$ range $\Gamma \left( N,V,E,\Delta \right)= \frac{\partial \Sigma}{\partial E}\Delta$.

For $N\gg 1$. $\ln \Gamma = \ln \Sigma$, Surface is growing as fast as volume.

\[S=k\ln \Gamma=k \ln \Sigma =  Nk \ln \left( \frac{V}{h^3}\left( \frac{4\pi m E}{3N} \right)^{3/2} \right)+\frac{3}{2}Nk\]

Now, calculate the properties of classical ideal gas.

\[E=\frac{3h^2N}{4\pi m V^{2/3}} \exp \left( \frac{2S}{3Nk}-1 \right)\]

\[T= \left( \frac{\partial E}{\partial S} \right) \Rightarrow E= \frac{3}{2}NkT\]
\[P= -\left( \frac{\partial E}{\partial V} \right)\Rightarrow P=\frac{2}{3}\frac{E}{V}\]

** Bibbs paradox
\[S=k \ln \frac{\Omega}{N!} = S_0-k \ln N +N\]

\[S=k\ln \Gamma=k \ln \Sigma =  Nk \ln \left( \frac{V}{Nh^3}\left( \frac{4\pi m E}{3N} \right)^{3/2} \right)+\frac{5}{2}Nk\]

* Elements of Ensemble Theory
\[
\left.
\begin{array}{rl}
\dot{q}_i&=&\frac{\partial H}{\partial p_i}\\
\dot{p}_i&=&-\frac{\partial H}{\partial q_i}\\
\end{array} \right\} i=1,2,3\dots 3N
\]

- Ensemble Average
\[
\left\langle f\right\rangle = \frac{\int f(q,p) \rho (q,p) d^{3N}q d^{3N}p}{\int \rho(q,p) d^{3N}q d^{3N}p}
\]
- Stationary State
\[
\frac{\partial \rho}{\partial t} = 0
\]

** Liouville's Theorem
- Equation of continuity
\[ \frac{\partial \rho }{\partial t}+\nabla \cdot \left( \rho v \right) = 0\]

\[ \frac{\partial \rho }{\partial t} + \sum_{i=1}^{3N} \left( \frac{\partial \rho}{\partial q_i} \dot{q}_i+ \frac{\partial \rho}{\partial p_i} \dot{p}_i \right)+\rho \sum_{i=1}^{3N}  \underbrace{ \left(\frac{\partial \dot{q}_i}{\partial q_i}+ \frac{\partial \dot{p}_i}{\partial p_i}\right)}_{\frac{\partial \dot{q}_i}{\partial q_i}=\frac{\partial^2 H}{\partial q_i\partial p_i}=-\frac{\partial \dot{p}_i}{\partial p_{i}}}  =0\]

- Liouville's Theorem
\[ \frac{d \rho}{d t}=\frac{\partial \rho}{\partial t}+ \left[ \rho ,H \right]=0\]

For stationary state ($\rho = \mathrm{const}$): $\left[ \rho ,H \right]=0$. However, other way to satisfy this is $\rho (p,q) = \rho \left( H(p,q) \right)$. The most natural choice in this class of ensembles is $\rho \propto \exp \left( -H/kT \right)$.

* Microcanonical ensemble
In this ensemble the macrostate of a system is defined by N,V and E.
\[
\left\{
\begin{array}{rl}
\rho \left( q,p \right) &=& \mathrm{const}. &\mbox{if $E-\frac{1}{2}\Delta \le H \le E+\frac{1}{2} \Delta$}\\
&=&  0 &\mbox{otherwise}
\end{array}
\right.
\]

Since the ensemble is a stationaty one, thus $\mbox{the ensemble average}=\mbox{long-time average}$.

** Examples
- fundamental volume

$\omega_{0}$ equivalent to one microstate.
\[ \Gamma = \frac{\omega}{\omega_0}\]

*** Classical Ideal Gas
\[\omega = \int d^{3N}p d^{3N}q\]

- Integrate over $q_{i}$ gives $V^{N}$.
- $p_{i}$ part
  \[2m \left( E-\frac{1}{2}\Delta \right) < \sum_{i=1}^{3N}y_i^{2} < 2m \left( E+\frac{1}{2}\Delta \right)\]
  Using $S_n \left( R \right) = \frac{2\pi^{n/2}}{\Gamma \left( n/2 \right)}R^{n-1}$.

\[\omega = \frac{\Delta}{E}V^N \frac{\left( 2\pi m E \right)^{3N/2}}{\left[ \frac{3N}{2}-1 \right]!} \]

\[\left( \frac{\omega}{\Gamma} \right)_{\mbox{asymp}} = \omega_0=h^{3N}\]

Generally if the system under study has $N$ degrees of freedom, the desired conversion factor is
\[\omega_0 = h^N\]

* Canonical Ensemble
Fixed temperature. The macrostate is defined through $N$, $V$ and $T$.

** Equilibrium Between A System And A Heat Reservoir
System $\left( E_r ; T \right)$

Reservoir $\left( E^{\prime}_r;T \right)$

\[P_r = \frac{\exp \left( -\beta E_r \right)}{\sum_r \exp \left( - \beta E_{r} \right)}\]

** A System in the canonical ensemble
Consider an ensemble of $N$ identical system. $n_r$ denotes the number of system at time $t$, have the energy value $E_r$, the set of numbers $\left\{ n_r \right\}$ must satisfy the obvious conditions.

\[
\left\{  
\begin{array}{rl}
\sum_r n_r &=& N\\
\sum_r n_r E_r &=& E = NU
\end{array}
\right.
\] 

\[
W \left\{ n_r \right\} = \frac{N!}{n_0!n_1!n_2! \dots}
\]

- Most probable mode $\left\{ n_r^{\star} \right\}$ when $W \left\{ n_r \right\}$ biggest.
- Average 
\[
\left\langle n_r \right\rangle = \frac{\sum_{\left\{ n_r \right\} n_r W \left( n_r \right) }}{\sum_{\left\{ n_r \right\} W \left\{ n_r \right\} }}
\]

In the limit of $N\Rightarrow \infty$. These two are the same.

- Canonical distribution
\[P_r = \frac{\left\langle n_r \right\rangle}{N}=\frac{\exp \left( -\beta E_r \right)}{\sum_r \exp \left( -\beta E_{r} \right)} \]

$\beta$ is determined by the equation
\[ U=- \frac{\partial}{\partial \beta} \ln \left\{ \sum_r \exp \left( -\beta E_r \right) \right\}\]

** Physical Significance Of The Various Statistical Quantities In The Caconical Ensemble
\[A = U-TS\]
\[dA = -SdT-PdV +\mu dN\]
\[
\left\{ 
\begin{array}{rl}
S &=& -\frac{dA}{dT}\\
P &=& \underbrace{-\frac{dA}{dV}}_{
\begin{array}{rl}
P=-\frac{\sum_{r} \frac{\partial E_r}{\partial V}\exp \left( - \beta E_r \right)}{\sum_r \exp \left( -\beta E_r \right)}\\
PdV=-\sum_r P_r dE_r = -dU\\
\end{array}
}\\
\mu &=& \frac{dA}{dN}\\
U &=& A+TS = \underbrace{A - T \frac{\partial A}{\partial T}}_{C_V = \left( \frac{\partial U}{\partial T} \right)_{N,V}=-T \left( \frac{\partial^2 A}{\partial T^2} \right)_{N,V}}=-T^2 \left[ \frac{\partial}{\partial T} \frac{A}{T} \right]= \left[ \frac{\partial \left( A/T \right)}{\partial \left( 1/T \right)} \right]
\end{array}
\right.
\]

Compare,
\[
\ln \left\{ \sum_r \exp \left( -\beta E_r \right) \right\}= -\beta A
\]

- Partition Function
\[
\left\{
\begin{array}{rl} 
A &=& -kT \ln Q_N \left( V,T \right)\\
Q_N \left( V,T \right) &=& \sum_r \exp \left( \frac{-E_r}{kT} \right)
\end{array}
\right.
\]

\[P_r = Q^{-1} \exp \left( -\beta E_r \right)\]

With degenerate
\[
Q_N = \sum_i g_i \exp \left( -\beta E_i \right)
\]

- Entropy
\[\left\langle \ln P_r \right\rangle = - \ln Q -\beta \left\langle E_r \right\rangle = \beta \left( A-U \right) = -S/k\]
\[S = -k \sum_r P_r \ln P_r \]

for $\Omega$ state all equally likely to occur. $p_r = 1/\Omega$

\[S=-k \sum \left\{ \frac{1}{\Omega} \ln \left( \frac{1}{\Omega} \right) \right\}=k \ln \Omega \]

- Density Of State
\[
P \left( E \right)dE =\frac{\exp \left( -\beta E \right) g \left( E \right)dE}{\int \exp \left( -\beta E \right) g \left( E \right)dE}
\]

\[
Q_N \left( V,T \right) = \int_0^{\infty} e^{-\beta E} g \left( E \right) dE
\]

$Q_N$ is the Laplace transform of $g(E)$.

** The Classical System
\[
Q_N \left( V,T \right) = \frac{1}{N! h^{3N}} \int e^{-\beta H \left( q,p \right)}d\omega
\]

*** Ideal Gas
\[H = \sum \left( \frac{p_i^2}{2m} \right)\]
\[
\begin{eqnarray}
Q_N &=& \frac{V^N}{N!h^{3N}}\left[ \int_0^{\infty}e^{-p^2/2mkT} \left( 4\pi p^2 dp \right) \right]^N \\
    &=& \frac{1}{N!} \left[ \frac{V}{h^3} \left( 2\pi mkT \right)^{3/2} \right]^{N}
\end{eqnarray}
\]

\[Q_N = \frac{1}{N!} Q_1^N \]
\[ A = -kT \ln Q_N = NkT \left[ \ln \left\{ \frac{N}{V} \left( \frac{h^2}{2\pi mkT} \right)^{3/2} \right\}-1 \right]\]

*** A System of Harmonic Oscillators (classical)

\[
H = \frac{1}{2} m \omega^2 q_i^2+\frac{1}{2m} p_i^2
\] 

\[
\begin{eqnarray}
Q_1 \left( \beta \right) &=& \int \int \exp \left\{ -\beta \left( \frac{1}{2} m \omega^2 q_i^2+\frac{1}{2m} p_i^2 \right) \right\} \frac{dp dq}{h}\\
&=& \frac{1}{\beta \hbar \omega}
\end{eqnarray}
\]

\[Q_N \left( \beta \right) = \left( \beta \hbar \omega \right)^{-N}\]

*** A System of Harmonic Oscillators (quantum)
\[\epsilon_n = \left( n+\frac{1}{2} \right) \hbar \omega\]

\[
Q_1=\sum_{n=0}^{\infty}e^{-\beta \left( n+1/2 \right)\hbar \omega}= \left\{ 2 \sinh \left( \frac{1}{2}\beta \hbar \omega \right) \right\}^{-1}
\]
*** The Statistics of Paramagnetism

------
[[file:index.org][Back to Index]]
